version: 0.2

phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - SET REPOSITORY_URI=221082214865.dkr.ecr.ap-south-1.amazonaws.com/wms-lebel-service
      - FOR /F "usebackq" %%i IN (`aws ecr get-login-password --region ap-south-1`) DO docker login --username AWS --password %%i %REPOSITORY_URI%
      - SET COMMIT_HASH=%CODEBUILD_RESOLVED_SOURCE_VERSION:~0,7%
      - FOR /F "tokens=2 delims=:" %%A IN ("%CODEBUILD_BUILD_ID%") DO SET IMAGE_TAG=build-%%A
  build:
    commands:
      - echo Build started on %date% %time%
      - echo Building the Docker image...
      - docker build -t %REPOSITORY_URI%:latest .
      - docker tag %REPOSITORY_URI%:latest %REPOSITORY_URI%:%IMAGE_TAG%
  post_build:
    commands:
      - echo Build completed on %date% %time%
      - echo Pushing the Docker images...
      - docker push %REPOSITORY_URI%:latest
      - docker push %REPOSITORY_URI%:%IMAGE_TAG%
      - echo Writing image definitions file...
      - SET DOCKER_CONTAINER_NAME=course-service
      - echo [{"name":"%DOCKER_CONTAINER_NAME%","imageUri":"%REPOSITORY_URI%:%IMAGE_TAG%"}] > imagedefinitions.json
      - echo Printing imagedefinitions.json...
      - type imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/course-service.jar
