spring:
  
   jpa:    hibernate:      ddl-auto: none    show-sql: true
   datasource:
         driverClassName: com.mysql.jdbc.Driver
         url: jdbc:mysql://localhost:3306/label_db
         username: root   
         password: root
---
 spring:
    profiles: h2    
    jpa:
       hibernate:
          ddl-auto: create-drop
       show-sql: true
    datasource:
       url: jdbc:h2:mem:mydb;MODE=Oracle;DB_CLOSE_ON_EXIT=FALSE 
       driver-class-name : org.h2.Driver
       hikari:
         connection-test-query: SELECT 1 FROM DUAL
         maximum-pool-size: 100
         