insert into LABEL(LABEL_ID,LABEL_TYPE,LABEL_NAME,PAER_SIZE,COMPANY,HAS_BARCODE,CREATED_BY,CREATED_ON,UPDATED_BY,UPDATED_ON,IS_ACTIVE)
values('123','CUSTOM','MVDC LABEL',null,'ROSS','N','992552',SYSDATE,'992552',SYSDATE,'Y');


insert into LABEL_WH(LABEL_WH_ID,LABEL_ID,WH_ID,CREATED_BY,CREATED_ON)values('12','123','EC','992552',SYSDATE);

commit;
